---
- name: ADD SSH
  hosts: all
  become: yes
  
  tasks:
  - name: Deploy SSH Key
    authorized_key: user=root
                    key="{{ lookup('file', '~/ssh_key/my_SSH_key.pub') }}"
                    state=present
  
  - name: Disable Password Authentication
    lineinfile:
                dest=/etc/ssh/sshd_config
                regexp='^PasswordAuthentication'
                line="PasswordAuthentication no"
                state=present
                backup=yes
  
  - name: Disable Root Login
    lineinfile:
                dest=/etc/ssh/sshd_config
                regexp='^PermitRootLogin'
                line="PermitRootLogin no"
                state=present
                backup=yes
    notify:
      - restart sshd
  
  handlers:
  - name: restart sshd
    service: name=sshd state=restarted
