---
- name: ADD SSH
  hosts: all
 # vars:
 #   - devops_password: '88888888dm'
 # gather_facts: no
 # remote_user: root
  become: yes
  
  tasks:
#  - name: Add a new user named devops
#    user:
#      name: devops
#      shell: /bin/bash
#      password: "{{ devops_password }}"
  
#  - name: Add devops user to the sudoers
#    copy:
#      dest: "/etc/sudoers.d/devops"
#        content: "devops  ALL=(ALL)  NOPASSWD: ALL"
  
  - name: Deploy SSH Key
    authorized_key: user=root
                    key="{{ lookup('file', '/home/devops/.ssh/my_SSH_key.pub') }}"
                    state=present
  
  - name: Disable Password Authentication
    lineinfile:
                dest=/etc/ssh/sshd_config
                regexp='^PasswordAuthentication'
                line="PasswordAuthentication no"
                state=present
                backup=yes
  
  - name: Disable Root Login
    lineinfile:
                dest=/etc/ssh/sshd_config
                regexp='^PermitRootLogin'
                line="PermitRootLogin no"
                state=present
                backup=yes
    notify:
      - restart sshd
  
  handlers:
  - name: restart sshd
    service: name=sshd state=restarted
