---
- name: SSH port
  hosts: all
 # vars:
 #  #   - devops_password: '88888888dm'
 #   # gather_facts: no
 #    # remote_user: root
  become: yes
        
  tasks:
        - name: Disable Root Login
  
          lineinfile:
                dest=/etc/ssh/sshd_config
                regexp='^Port 22'
                line="Port 253"
                state=present
                backup=yes
          notify:
                - restart sshd
  
  handlers:
  - name: restart sshd
    service: name=sshd state=restarted
